version: "3"

services:
  app:
    image: "connectima/image"
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-cl8atb2uuipc73eoqi30-a:5432/probna_baza"
    depends_on:
      - imdb-db-container
  imdb-db-container:
    image: "postgres:13-alpine"
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_DB=probna_baza"
      - "POSTGRES_USER=probna_baza_user"
      - "POSTGRES_PASSWORD=b5N3mDCgjMxYOIl55cpS1as1Jd5uTXQ3"
